CREATE TABLE persona_weapon_stats (
    persona_id BIGINT NOT NULL,
    guid UUID NOT NULL,
    slug TEXT,
    name TEXT,
    category TEXT,
    category_sid TEXT,
    code TEXT,
    type TEXT,
    image_config TEXT,
    unlock_image_config TEXT,
    service_stars INT,
    service_stars_progress FLOAT,
    kills INT,
    kills_delta INT,
    kills_per_minute_delta FLOAT,
    deaths INT,
    headshots INT,
    shots_fired BIGINT,
    shots_hit BIGINT,
    accuracy FLOAT,
    score BIGINT,
    time_equipped BIGINT,
    time_equipped_delta FLOAT,
    unlocked BOOLEAN,
    started_with BOOLEAN,
    kit TEXT,
    duplicate_of TEXT,
    weapon TEXT,
    unlocks JSONB,
    UNIQUE (persona_id, guid)
);
